=== javaintake39/JAXB-with-XML/src/jaxlab2/history.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="history" type="container">
        
    </xs:element>
    <xs:complexType name="messageInfo">
        <xs:sequence>
            <xs:element type="xs:byte" name="fromPhone"/>
            <xs:element type="xs:byte" name="toPhone"/>
            <xs:element type="xs:string" name="content"/>
            <xs:element type="xs:date" name="date"/>
            <xs:element type="xs:string" name="fontColor"/>
            <xs:element type="xs:string" name="fontFamily"/>
            <xs:element type="xs:byte" name="fontSize"/>
            <xs:element type="xs:string" name="isUnderline"/>
            <xs:element type="xs:string" name="isBold"/>
            <xs:element type="xs:string" name="isItalic"/>
            <xs:element type="xs:string" name="backgroundColor"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="content">
        <xs:sequence>
            <xs:element name="message" maxOccurs="unbounded" minOccurs="0" type="messageInfo"> 
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="container">
        <xs:sequence>
            <xs:element name="messages" type="content">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== javaintake39/JAXB-with-XML/src/jaxlab2/history.xml
<?xml version="1.0" encoding="UTF-8"?>
<history xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="history.xsd">
    <messages>
        <message>
            <fromPhone>010</fromPhone>
            <toPhone>010</toPhone>
            <content>Hello ya gma3a</content>
            <date>2019-02-20-08:00</date>
            <fontColor>#000000</fontColor>
            <fontFamily>serif</fontFamily>
            <fontSize>24</fontSize>
            <isUnderline>true</isUnderline>
            <isBold>false</isBold>
            <isItalic>false</isItalic>
            <backgroundColor>#000FFF</backgroundColor>
        </message>
        <message>
            <fromPhone>011</fromPhone>
            <toPhone>013</toPhone>
            <content>This is Second message</content>
            <date>2019-04-22-06:00</date>
            <fontColor>#FFFFFF</fontColor>
            <fontFamily>Arial</fontFamily>
            <fontSize>30</fontSize>
            <isUnderline>true</isUnderline>
            <isBold>false</isBold>
            <isItalic>false</isItalic>
            <backgroundColor>#000FFF</backgroundColor>
        </message>
        <message>
            <fromPhone>013</fromPhone>
            <toPhone>015</toPhone>
            <content>This is third message</content>
            <date>2019-09-22-08:50</date>
            <fontColor>#FC0011</fontColor>
            <fontFamily>sans-serif</fontFamily>
            <fontSize>20</fontSize>
            <isUnderline>true</isUnderline>
            <isBold>false</isBold>
            <isItalic>false</isItalic>
            <backgroundColor>#000FFF</backgroundColor>
        </message>
    </messages>
</history>
